// Generated by CoffeeScript 1.3.1
(function() {
  var alreadyWinning, list, names, obj, people, randomFromTo, used,
    __indexOf = [].indexOf || function(item) { for (var i = 0, l = this.length; i < l; i++) { if (i in this && this[i] === item) return i; } return -1; };

  $(document).ready(function() {});

  used = [];

  obj = {
    1: 0,
    2: 0,
    3: 0
  };

  names = {
    1: "Nico",
    2: "Andrin",
    3: "Joris"
  };

  list = $(".rankings");

  $('body').click(function() {
    used = [];
    list.html('');
    return people(3);
  });

  randomFromTo = function(from, to) {
    return Math.floor(Math.random() * (to - from + 1) + from);
  };

  alreadyWinning = function(person, peeps) {
    while (__indexOf.call(used, person) >= 0) {
      person = names[randomFromTo(1, peeps)];
    }
    used.push(person);
    return list.append("<li>" + person + "</li>");
  };

  people = function(peeps) {
    var i, person, _results;
    i = 0;
    _results = [];
    while (i < peeps) {
      person = names[randomFromTo(1, peeps)];
      alreadyWinning(person, peeps);
      _results.push(i++);
    }
    return _results;
  };

}).call(this);
